# Generated by roux build from Bottom.rocstache. DO NOT EDIT.
# The template's contract only: markup changes leave this file alone.
import pf.Rocstache

Bottom :: [].{

	## What `Bottom.rocstache` reads, inferred from its tags.
	Ctx : {}

	## The page: the template as compiled into the app, rendered by the host.
	render! : Ctx => Str
	render! = |_ctx| Rocstache.compiled_render!(0x2cec925d5d980c86, Box.box(0.U8))
}
