# Generated by roux build from CompetitorsPage.rocstache. DO NOT EDIT.
# The template's contract only: markup changes leave this file alone.
import pf.Rocstache

CompetitorsPage :: [].{

	## What `CompetitorsPage.rocstache` reads, inferred from its tags.
	Ctx : {
		home : Bool,
		nav : List({ current : Bool, href : Str, label : Str }),
		pins : List({ name : Str, version : Str }),
		title : Str,
	}

	## The page: the template as compiled into the app, rendered by the host.
	render! : Ctx => Str
	render! = |ctx| Rocstache.compiled_render!(0xe7dcb3401ecbe5f1, Box.box(ctx))
}
