# Generated by roux build from ContributePage.rocstache. DO NOT EDIT.
# The template's contract only: markup changes leave this file alone.
import pf.Rocstache

ContributePage :: [].{

	## What `ContributePage.rocstache` reads, inferred from its tags.
	Ctx : {
		home : Bool,
		nav : List({ current : Bool, href : Str, label : Str }),
		title : Str,
	}

	## The page: the template as compiled into the app, rendered by the host.
	render! : Ctx => Str
	render! = |ctx| Rocstache.compiled_render!(0xd0066e710eac4e8d, Box.box(ctx))
}
