# Generated by roux build from HistoryClasses.rocstache. DO NOT EDIT.
# The template's contract only: markup changes leave this file alone.
import pf.Rocstache

HistoryClasses :: [].{

	## What `HistoryClasses.rocstache` reads, inferred from its tags.
	Ctx : {
		classes : List(
			{
				charts : List(
					{
						dates : List({ label : Str, x : Str }),
						empty : Bool,
						lines : List(
							{
								competitor : Str,
								dots : List(
									{
										cx : Str,
										cy : Str,
										r : Str,
										title : Str,
									},
								),
								drawn : Bool,
								label_x : Str,
								label_y : Str,
								path : Str,
							},
						),
						ticks : List(
							{ label : Str, line_y : Str, text_y : Str },
						),
						title : Str,
					},
				),
				title : Str,
			},
		),
		tabs : List({ action : Str, current : Bool, href : Str, label : Str }),
	}

	## The page: the template as compiled into the app, rendered by the host.
	render! : Ctx => Str
	render! = |ctx| Rocstache.compiled_render!(0x30f68bed3966a7ba, Box.box(ctx))
}
