# Generated by roux build from RaceClasses.rocstache. DO NOT EDIT.
# The template's contract only: markup changes leave this file alone.
import pf.Rocstache

RaceClasses :: [].{

	## What `RaceClasses.rocstache` reads, inferred from its tags.
	Ctx : {
		classes : List(
			{
				machines : List({ role : Str, text : Str }),
				name : Str,
				open : List(
					{
						caption : Str,
						lines : List(
							{
								competitor : Str,
								dots : List(
									{
										cx : Str,
										cy : Str,
										hollow : Bool,
										title : Str,
									},
								),
								label_x : Str,
								label_y : Str,
								path : Str,
							},
						),
						measure : Str,
						ticks_x : List({ label : Str, x : Str }),
						ticks_y : List(
							{ label : Str, line_y : Str, text_y : Str },
						),
						title : Str,
					},
				),
				strips : List(
					{
						rows : List(
							{
								competitor : Str,
								high : Str,
								hollow : Bool,
								low : Str,
								ranged : Bool,
								reach : Str,
								share : Str,
								tip : Str,
								valid : Bool,
								value : Str,
							},
						),
						summary : Str,
						table : List(
							{
								competitor : Str,
								cpu : Str,
								limit : Str,
								loader : Str,
								net : Str,
								note : Str,
								p95 : Str,
								p99 : Str,
								p999 : Str,
								rounds : Str,
								rps : Str,
								rss : Str,
								spread : Str,
								steal : Str,
								valid : Bool,
							},
						),
						title : Str,
					},
				),
				title : Str,
			},
		),
		id : Str,
		tabs : List({ action : Str, current : Bool, href : Str, label : Str }),
	}

	## The page: the template as compiled into the app, rendered by the host.
	render! : Ctx => Str
	render! = |ctx| Rocstache.compiled_render!(0x4abec41840da2809, Box.box(ctx))
}
