# Generated by roux build from the app's templates. DO NOT EDIT.
# The contracts spelled out, so each template's module can import this one.

Templates :: [].{
	## Every template of the app, a tag each, holding what it reads.
	Template : [
		AboutPage({ home : Bool, nav : List({ current : Bool, href : Str, label : Str }), title : Str }),
		Bottom({}),
		CompetitorsPage({ home : Bool, nav : List({ current : Bool, href : Str, label : Str }), pins : List({ name : Str, version : Str }), title : Str }),
		ContributePage({ home : Bool, nav : List({ current : Bool, href : Str, label : Str }), title : Str }),
		HistoryClasses({ classes : List({ charts : List({ dates : List({ label : Str, x : Str }), empty : Bool, lines : List({ competitor : Str, dots : List({ cx : Str, cy : Str, r : Str, title : Str }), drawn : Bool, label_x : Str, label_y : Str, path : Str }), ticks : List({ label : Str, line_y : Str, text_y : Str }), title : Str }), title : Str }), tabs : List({ action : Str, current : Bool, href : Str, label : Str }) }),
		HistoryPage({ classes : List({ charts : List({ dates : List({ label : Str, x : Str }), empty : Bool, lines : List({ competitor : Str, dots : List({ cx : Str, cy : Str, r : Str, title : Str }), drawn : Bool, label_x : Str, label_y : Str, path : Str }), ticks : List({ label : Str, line_y : Str, text_y : Str }), title : Str }), title : Str }), competitors : List(Str), home : Bool, nav : List({ current : Bool, href : Str, label : Str }), note : Str, tabs : List({ action : Str, current : Bool, href : Str, label : Str }), title : Str, waiting : Bool }),
		IndexPage({ classes : List({ machines : List({ role : Str, text : Str }), name : Str, open : List({ caption : Str, lines : List({ competitor : Str, dots : List({ cx : Str, cy : Str, hollow : Bool, title : Str }), label_x : Str, label_y : Str, path : Str }), measure : Str, ticks_x : List({ label : Str, x : Str }), ticks_y : List({ label : Str, line_y : Str, text_y : Str }), title : Str }), strips : List({ rows : List({ competitor : Str, high : Str, hollow : Bool, low : Str, ranged : Bool, reach : Str, share : Str, tip : Str, valid : Bool, value : Str }), summary : Str, table : List({ competitor : Str, cpu : Str, limit : Str, loader : Str, net : Str, note : Str, p95 : Str, p99 : Str, p999 : Str, rounds : Str, rps : Str, rss : Str, spread : Str, steal : Str, valid : Bool }), title : Str }), title : Str }), commits : List({ name : Str, short : Str, url : Str }), competitors : List(Str), home : Bool, id : Str, nav : List({ current : Bool, href : Str, label : Str }), racer : List({ items : List(Str), text : Str }), ready : Bool, started : Str, tabs : List({ action : Str, current : Bool, href : Str, label : Str }), timed : Bool, title : Str, took : Str }),
		MethodPage({ home : Bool, nav : List({ current : Bool, href : Str, label : Str }), title : Str }),
		NotFoundPage({ home : Bool, nav : List({ current : Bool, href : Str, label : Str }), title : Str }),
		RaceClasses({ classes : List({ machines : List({ role : Str, text : Str }), name : Str, open : List({ caption : Str, lines : List({ competitor : Str, dots : List({ cx : Str, cy : Str, hollow : Bool, title : Str }), label_x : Str, label_y : Str, path : Str }), measure : Str, ticks_x : List({ label : Str, x : Str }), ticks_y : List({ label : Str, line_y : Str, text_y : Str }), title : Str }), strips : List({ rows : List({ competitor : Str, high : Str, hollow : Bool, low : Str, ranged : Bool, reach : Str, share : Str, tip : Str, valid : Bool, value : Str }), summary : Str, table : List({ competitor : Str, cpu : Str, limit : Str, loader : Str, net : Str, note : Str, p95 : Str, p99 : Str, p999 : Str, rounds : Str, rps : Str, rss : Str, spread : Str, steal : Str, valid : Bool }), title : Str }), title : Str }), id : Str, tabs : List({ action : Str, current : Bool, href : Str, label : Str }) }),
		Top({ home : Bool, nav : List({ current : Bool, href : Str, label : Str }), title : Str }),
		WorkloadsPage({ cards : List({ route : Str, spec : Str, summary : Str, title : Str }), home : Bool, ladder : Str, loader_limit : Str, measure : Str, nav : List({ current : Bool, href : Str, label : Str }), ready : Bool, rounds : Str, shares : Str, title : Str, warmup : Str }),
	]

	## The layouts these templates were compiled for: the host renders
	## only a value made for its program's.
	layouts : U64
	layouts = 0x22adf9eae1d52359
}
