# Generated by roux build from WorkloadsPage.rocstache. DO NOT EDIT.
# The template's contract only: markup changes leave this file alone.
import pf.Rocstache

WorkloadsPage :: [].{

	## What `WorkloadsPage.rocstache` reads, inferred from its tags.
	Ctx : {
		cards : List({ route : Str, spec : Str, summary : Str, title : Str }),
		home : Bool,
		ladder : Str,
		loader_limit : Str,
		measure : Str,
		nav : List({ current : Bool, href : Str, label : Str }),
		ready : Bool,
		rounds : Str,
		shares : Str,
		title : Str,
		warmup : Str,
	}

	## The page: the template as compiled into the app, rendered by the host.
	render! : Ctx => Str
	render! = |ctx| Rocstache.compiled_render!(0x6ddd6c4f985d2171, Box.box(ctx))
}
