# Generated by roux build from Menu.rocstache. DO NOT EDIT.
# The template's contract only: markup changes leave this file alone.
import pf.Rocstache

Menu :: [].{

	## The race's menu: the prices are numbers, so the contract is declared.
	Ctx : { dishes : List({ name : Str, price : U32 }) }

	## The page: the template as compiled into the app, rendered by the host.
	render! : Ctx => Str
	render! = |ctx| Rocstache.compiled_render!(0x5485712b3f02f3d8, Box.box(ctx))
}
