# Generated by roux build from Menu.rocstache. DO NOT EDIT.
# Its contract only: markup changes leave this file alone.
import pf.Rocstache

Menu :: [].{

	## The race's menu: the prices are numbers, so the contract is declared.
	Ctx : { dishes : List({ name : Str, price : U32 }) }

	## The page, rendered by the host from the template's bytecode.
	render! : Ctx => Rocstache.Html
	render! = |ctx| Rocstache.render!(0, Box.box(ctx))
}
