# Generated by roux build from Menu.rocstache. DO NOT EDIT.
# Its contract only: markup changes leave this file alone.
import pf.Rocstache
import Templates

Menu :: [].{

	## The race's menu: the prices are numbers, so the contract is declared.
	Ctx : { dishes : List({ name : Str, price : U32 }) }

	## The template's value: what a response sends, rendered by the
	## host from the template's bytecode as it is sent.
	template : Ctx -> Rocstache.Template(Templates.Template)
	template = |ctx| { layouts: Templates.layouts, template: Menu(ctx) }
}
