# Generated by roux-db from Heads.sql. DO NOT EDIT.
import pf.Sqlite

## The queries of `Heads.sql`, typed by SQLite against `schema.sql`. Each runs a
## statement the host prepared at startup (`Database.roc`).
Heads :: [].{

	## `set`, Heads.sql:3: no rows.
	set! : Sqlite.Write, { repository : Str, commit_sha : Str } => Try({}, [DbErr(Sqlite.Err)])
	set! = |db, params| {
		_ = Sqlite.run_write!(db, 0, [Sqlite.Param.str(params.repository), Sqlite.Param.str(params.commit_sha)])? # Heads.sql:6
		Ok({})
	}

	## A row of `all`.
	All : { repository : Str, commit_sha : Str, seen_at : Str }

	## `all`, Heads.sql:10: the rows, at most `:many`'s bound (more is `TooManyRows`).
	all! : Sqlite.Read => Try(List(All), [DbErr(Sqlite.Err)])
	all! = |db| {
		rows = Sqlite.run_read!(db, 1, [])? # Heads.sql:11
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2] => { repository: Sqlite.Cell.str(c0), commit_sha: Sqlite.Cell.str(c1), seen_at: Sqlite.Cell.str(c2) }
					_ => crash "roux-db: Heads.all: a row the host should have refused"
				},
			),
		)
	}
}
