# Generated by roux-db from Health.sql. DO NOT EDIT.
import pf.Sqlite

## The queries of `Health.sql`, typed by SQLite against `schema.sql`. Each runs a
## statement the host prepared at startup (`Database.roc`).
Health :: [].{

	## A row of `ping`.
	Ping : { one : I64 }

	## `ping`, Health.sql:1: one row, or `NotFound`.
	ping! : Sqlite.Read => Try(Ping, [NotFound, DbErr(Sqlite.Err)])
	ping! = |db| {
		rows = Sqlite.run_read!(db, 2, [])? # Health.sql:3
		match rows {
			[] => Err(NotFound)
			[[c0]] => Ok({ one: Sqlite.Cell.i64(c0) })
			_ => crash "roux-db: Health.ping: rows the host should have refused"
		}
	}
}
