# Generated by roux-db from Pages.sql. DO NOT EDIT.
import pf.Sqlite

## The queries of `Pages.sql`, typed by SQLite against `schema.sql`. Each runs a
## statement the host prepared at startup (`Database.roc`).
Pages :: [].{

	## A row of `latest`.
	Latest : { id : Str }

	## `latest`, Pages.sql:5: one row, or `NotFound`.
	latest! : Sqlite.Read => Try(Latest, [NotFound, DbErr(Sqlite.Err)])
	latest! = |db| {
		rows = Sqlite.run_read!(db, 3, [])? # Pages.sql:6
		match rows {
			[] => Err(NotFound)
			[[c0]] => Ok({ id: Sqlite.Cell.str(c0) })
			_ => crash "roux-db: Pages.latest: rows the host should have refused"
		}
	}

	## A row of `run`.
	Run : { id : Str, status : Str, trigger : Str, started_at : Str, seconds : F64, cost_usd : F64 }

	## `run`, Pages.sql:8: one row, or `NotFound`.
	run! : Sqlite.Read, { id : Str } => Try(Run, [NotFound, DbErr(Sqlite.Err)])
	run! = |db, params| {
		rows = Sqlite.run_read!(db, 4, [Sqlite.Param.str(params.id)])? # Pages.sql:10
		match rows {
			[] => Err(NotFound)
			[[c0, c1, c2, c3, c4, c5]] => Ok({ id: Sqlite.Cell.str(c0), status: Sqlite.Cell.str(c1), trigger: Sqlite.Cell.str(c2), started_at: Sqlite.Cell.str(c3), seconds: Sqlite.Cell.f64(c4), cost_usd: Sqlite.Cell.f64(c5) })
			_ => crash "roux-db: Pages.run: rows the host should have refused"
		}
	}

	## A row of `commits`.
	Commits : { repository : Str, commit_sha : Str, new : Bool }

	## `commits`, Pages.sql:12: the rows, at most `:many`'s bound (more is `TooManyRows`).
	commits! : Sqlite.Read, { run_id : Str } => Try(List(Commits), [DbErr(Sqlite.Err)])
	commits! = |db, params| {
		rows = Sqlite.run_read!(db, 5, [Sqlite.Param.str(params.run_id)])? # Pages.sql:15
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2] => { repository: Sqlite.Cell.str(c0), commit_sha: Sqlite.Cell.str(c1), new: Sqlite.Cell.bool(c2) }
					_ => crash "roux-db: Pages.commits: a row the host should have refused"
				},
			),
		)
	}

	## A row of `versions`.
	Versions : { name : Str, version : Str }

	## `versions`, Pages.sql:17: the rows, at most `:many`'s bound (more is `TooManyRows`).
	versions! : Sqlite.Read, { run_id : Str } => Try(List(Versions), [DbErr(Sqlite.Err)])
	versions! = |db, params| {
		rows = Sqlite.run_read!(db, 6, [Sqlite.Param.str(params.run_id)])? # Pages.sql:19
		Ok(
			rows.map(
				|row| match row {
					[c0, c1] => { name: Sqlite.Cell.str(c0), version: Sqlite.Cell.str(c1) }
					_ => crash "roux-db: Pages.versions: a row the host should have refused"
				},
			),
		)
	}

	## A row of `competitors`.
	Competitors : { name : Str }

	## `competitors`, Pages.sql:21: the rows, at most `:many`'s bound (more is `TooManyRows`).
	competitors! : Sqlite.Read, { run_id : Str } => Try(List(Competitors), [DbErr(Sqlite.Err)])
	competitors! = |db, params| {
		rows = Sqlite.run_read!(db, 7, [Sqlite.Param.str(params.run_id)])? # Pages.sql:23
		Ok(
			rows.map(
				|row| match row {
					[c0] => { name: Sqlite.Cell.str(c0) }
					_ => crash "roux-db: Pages.competitors: a row the host should have refused"
				},
			),
		)
	}

	## A row of `workloads`.
	Workloads : { name : Str, title : Str, summary : Str }

	## `workloads`, Pages.sql:25: the rows, at most `:many`'s bound (more is `TooManyRows`).
	workloads! : Sqlite.Read, { run_id : Str } => Try(List(Workloads), [DbErr(Sqlite.Err)])
	workloads! = |db, params| {
		rows = Sqlite.run_read!(db, 8, [Sqlite.Param.str(params.run_id)])? # Pages.sql:27
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2] => { name: Sqlite.Cell.str(c0), title: Sqlite.Cell.str(c1), summary: Sqlite.Cell.str(c2) }
					_ => crash "roux-db: Pages.workloads: a row the host should have refused"
				},
			),
		)
	}

	## A row of `classes`.
	Classes : { name : Str, label : Str, title : Str }

	## `classes`, Pages.sql:29: the rows, at most `:many`'s bound (more is `TooManyRows`).
	classes! : Sqlite.Read, { run_id : Str } => Try(List(Classes), [DbErr(Sqlite.Err)])
	classes! = |db, params| {
		rows = Sqlite.run_read!(db, 9, [Sqlite.Param.str(params.run_id)])? # Pages.sql:31
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2] => { name: Sqlite.Cell.str(c0), label: Sqlite.Cell.str(c1), title: Sqlite.Cell.str(c2) }
					_ => crash "roux-db: Pages.classes: a row the host should have refused"
				},
			),
		)
	}

	## A row of `machines`.
	Machines : { role : Str, class : Str, size : Str, cpu : Str, cpus : I64, kernel : Str, cpu_wanted : Str, cpu_matched : Bool, attempts : I64 }

	## `machines`, Pages.sql:33: the rows, at most `:many`'s bound (more is `TooManyRows`).
	machines! : Sqlite.Read, { run_id : Str } => Try(List(Machines), [DbErr(Sqlite.Err)])
	machines! = |db, params| {
		rows = Sqlite.run_read!(db, 10, [Sqlite.Param.str(params.run_id)])? # Pages.sql:36
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2, c3, c4, c5, c6, c7, c8] => { role: Sqlite.Cell.str(c0), class: Sqlite.Cell.str(c1), size: Sqlite.Cell.str(c2), cpu: Sqlite.Cell.str(c3), cpus: Sqlite.Cell.i64(c4), kernel: Sqlite.Cell.str(c5), cpu_wanted: Sqlite.Cell.str(c6), cpu_matched: Sqlite.Cell.bool(c7), attempts: Sqlite.Cell.i64(c8) }
					_ => crash "roux-db: Pages.machines: a row the host should have refused"
				},
			),
		)
	}

	## A row of `results`.
	Results : { class : Str, workload : Str, competitor : Str, valid : Bool, note : Str, median_rps : F64, median_p95_ms : F64, median_p99_ms : F64, median_p999_ms : F64 }

	## `results`, Pages.sql:39: the rows, at most `:many`'s bound (more is `TooManyRows`).
	results! : Sqlite.Read, { run_id : Str } => Try(List(Results), [DbErr(Sqlite.Err)])
	results! = |db, params| {
		rows = Sqlite.run_read!(db, 11, [Sqlite.Param.str(params.run_id)])? # Pages.sql:42
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2, c3, c4, c5, c6, c7, c8] => { class: Sqlite.Cell.str(c0), workload: Sqlite.Cell.str(c1), competitor: Sqlite.Cell.str(c2), valid: Sqlite.Cell.bool(c3), note: Sqlite.Cell.str(c4), median_rps: Sqlite.Cell.f64(c5), median_p95_ms: Sqlite.Cell.f64(c6), median_p99_ms: Sqlite.Cell.f64(c7), median_p999_ms: Sqlite.Cell.f64(c8) }
					_ => crash "roux-db: Pages.results: a row the host should have refused"
				},
			),
		)
	}

	## A row of `rounds`.
	Rounds : { class : Str, workload : Str, competitor : Str, rps : F64, p99_ms : F64, cpu_busy_pct : F64, steal_pct : F64, rss_kib : F64, loader_cpu_busy_pct : F64, net_rx_mbps : F64, net_tx_mbps : F64, tcp_retransmits : F64, load_seconds : F64 }

	## `rounds`, Pages.sql:46: the rows, at most `:many`'s bound (more is `TooManyRows`).
	rounds! : Sqlite.Read, { run_id : Str } => Try(List(Rounds), [DbErr(Sqlite.Err)])
	rounds! = |db, params| {
		rows = Sqlite.run_read!(db, 12, [Sqlite.Param.str(params.run_id)])? # Pages.sql:50
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12] => { class: Sqlite.Cell.str(c0), workload: Sqlite.Cell.str(c1), competitor: Sqlite.Cell.str(c2), rps: Sqlite.Cell.f64(c3), p99_ms: Sqlite.Cell.f64(c4), cpu_busy_pct: Sqlite.Cell.f64(c5), steal_pct: Sqlite.Cell.f64(c6), rss_kib: Sqlite.Cell.f64(c7), loader_cpu_busy_pct: Sqlite.Cell.f64(c8), net_rx_mbps: Sqlite.Cell.f64(c9), net_tx_mbps: Sqlite.Cell.f64(c10), tcp_retransmits: Sqlite.Cell.f64(c11), load_seconds: Sqlite.Cell.f64(c12) }
					_ => crash "roux-db: Pages.rounds: a row the host should have refused"
				},
			),
		)
	}

	## A row of `steps`.
	Steps : { class : Str, workload : Str, competitor : Str, share : F64, offered_rps : F64, achieved_rps : F64, p99_ms : F64, p999_ms : F64, cpu_busy_pct : F64, loader_cpu_busy_pct : F64 }

	## `steps`, Pages.sql:55: the rows, at most `:many`'s bound (more is `TooManyRows`).
	steps! : Sqlite.Read, { run_id : Str } => Try(List(Steps), [DbErr(Sqlite.Err)])
	steps! = |db, params| {
		rows = Sqlite.run_read!(db, 13, [Sqlite.Param.str(params.run_id)])? # Pages.sql:57
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2, c3, c4, c5, c6, c7, c8, c9] => { class: Sqlite.Cell.str(c0), workload: Sqlite.Cell.str(c1), competitor: Sqlite.Cell.str(c2), share: Sqlite.Cell.f64(c3), offered_rps: Sqlite.Cell.f64(c4), achieved_rps: Sqlite.Cell.f64(c5), p99_ms: Sqlite.Cell.f64(c6), p999_ms: Sqlite.Cell.f64(c7), cpu_busy_pct: Sqlite.Cell.f64(c8), loader_cpu_busy_pct: Sqlite.Cell.f64(c9) }
					_ => crash "roux-db: Pages.steps: a row the host should have refused"
				},
			),
		)
	}

	## A row of `history`.
	History : { id : Str, started_at : Str, class : Str, workload : Str, competitor : Str, valid : Bool, median_rps : F64 }

	## `history`, Pages.sql:63: the rows, at most `:many`'s bound (more is `TooManyRows`).
	history! : Sqlite.Read => Try(List(History), [DbErr(Sqlite.Err)])
	history! = |db| {
		rows = Sqlite.run_read!(db, 14, [])? # Pages.sql:65
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2, c3, c4, c5, c6] => { id: Sqlite.Cell.str(c0), started_at: Sqlite.Cell.str(c1), class: Sqlite.Cell.str(c2), workload: Sqlite.Cell.str(c3), competitor: Sqlite.Cell.str(c4), valid: Sqlite.Cell.bool(c5), median_rps: Sqlite.Cell.f64(c6) }
					_ => crash "roux-db: Pages.history: a row the host should have refused"
				},
			),
		)
	}

	## A row of `recent`.
	Recent : { id : Str, trigger : Str, status : Str, reason : Str, started_at : Str, finished_at : Sqlite.Nullable(Str) }

	## `recent`, Pages.sql:72: the rows, at most `:many`'s bound (more is `TooManyRows`).
	recent! : Sqlite.Read => Try(List(Recent), [DbErr(Sqlite.Err)])
	recent! = |db| {
		rows = Sqlite.run_read!(db, 15, [])? # Pages.sql:73
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2, c3, c4, c5] => { id: Sqlite.Cell.str(c0), trigger: Sqlite.Cell.str(c1), status: Sqlite.Cell.str(c2), reason: Sqlite.Cell.str(c3), started_at: Sqlite.Cell.str(c4), finished_at: Sqlite.Cell.nullable_str(c5) }
					_ => crash "roux-db: Pages.recent: a row the host should have refused"
				},
			),
		)
	}

	## A row of `class_status`.
	ClassStatus : { class : Str, status : Str, reason : Str, seconds : F64 }

	## `class_status`, Pages.sql:76: the rows, at most `:many`'s bound (more is `TooManyRows`).
	class_status! : Sqlite.Read, { run_id : Str } => Try(List(ClassStatus), [DbErr(Sqlite.Err)])
	class_status! = |db, params| {
		rows = Sqlite.run_read!(db, 16, [Sqlite.Param.str(params.run_id)])? # Pages.sql:78
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2, c3] => { class: Sqlite.Cell.str(c0), status: Sqlite.Cell.str(c1), reason: Sqlite.Cell.str(c2), seconds: Sqlite.Cell.f64(c3) }
					_ => crash "roux-db: Pages.class_status: a row the host should have refused"
				},
			),
		)
	}

	## A row of `result_count`.
	ResultCount : { results : I64 }

	## `result_count`, Pages.sql:82: one row, or `NotFound`.
	result_count! : Sqlite.Read, { run_id : Str } => Try(ResultCount, [NotFound, DbErr(Sqlite.Err)])
	result_count! = |db, params| {
		rows = Sqlite.run_read!(db, 17, [Sqlite.Param.str(params.run_id)])? # Pages.sql:85
		match rows {
			[] => Err(NotFound)
			[[c0]] => Ok({ results: Sqlite.Cell.i64(c0) })
			_ => crash "roux-db: Pages.result_count: rows the host should have refused"
		}
	}
}
