# Generated by roux-db from Requests.sql. DO NOT EDIT.
import pf.Sqlite

## The queries of `Requests.sql`, typed by SQLite against `schema.sql`. Each runs a
## statement the host prepared at startup (`Database.roc`).
Requests :: [].{

	## A row of `add`.
	Add : { id : I64, asked_at : Str }

	## `add`, Requests.sql:3: one row, or `NotFound`.
	add! : Sqlite.Write, { kind : Str, asked_by : Str } => Try(Add, [NotFound, DbErr(Sqlite.Err)])
	add! = |db, params| {
		rows = Sqlite.run_write!(db, 18, [Sqlite.Param.str(params.kind), Sqlite.Param.str(params.asked_by)])? # Requests.sql:6
		match rows {
			[] => Err(NotFound)
			[[c0, c1]] => Ok({ id: Sqlite.Cell.i64(c0), asked_at: Sqlite.Cell.str(c1) })
			_ => crash "roux-db: Requests.add: rows the host should have refused"
		}
	}

	## A row of `waiting`.
	Waiting : { id : I64, kind : Str, asked_by : Str, asked_at : Str }

	## `waiting`, Requests.sql:10: the rows, at most `:many`'s bound (more is `TooManyRows`).
	waiting! : Sqlite.Read => Try(List(Waiting), [DbErr(Sqlite.Err)])
	waiting! = |db| {
		rows = Sqlite.run_read!(db, 19, [])? # Requests.sql:11
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2, c3] => { id: Sqlite.Cell.i64(c0), kind: Sqlite.Cell.str(c1), asked_by: Sqlite.Cell.str(c2), asked_at: Sqlite.Cell.str(c3) }
					_ => crash "roux-db: Requests.waiting: a row the host should have refused"
				},
			),
		)
	}

	## `take`, Requests.sql:14: no rows.
	take! : Sqlite.Write, { id : I64 } => Try({}, [DbErr(Sqlite.Err)])
	take! = |db, params| {
		_ = Sqlite.run_write!(db, 20, [Sqlite.Param.i64(params.id)])? # Requests.sql:16
		Ok({})
	}
}
