# Generated by roux-db from Runs.sql. DO NOT EDIT.
import pf.Sqlite

## The queries of `Runs.sql`, typed by SQLite against `schema.sql`. Each runs a
## statement the host prepared at startup (`Database.roc`).
Runs :: [].{

	## `add`, Runs.sql:4: no rows.
	add! : Sqlite.Write, { id : Str, request_id : Sqlite.Nullable(I64), trigger : Str, status : Str, reason : Str, where_raced : Str, started_at : Str, worker_token : Sqlite.Nullable(Str) } => Try({}, [DbErr(Sqlite.Err)])
	add! = |db, params| {
		_ = Sqlite.run_write!(db, 26, [Sqlite.Param.str(params.id), Sqlite.Param.nullable_i64(params.request_id), Sqlite.Param.str(params.trigger), Sqlite.Param.str(params.status), Sqlite.Param.str(params.reason), Sqlite.Param.str(params.where_raced), Sqlite.Param.str(params.started_at), Sqlite.Param.nullable_str(params.worker_token)])? # Runs.sql:13
		Ok({})
	}

	## `add_commit`, Runs.sql:19: no rows.
	add_commit! : Sqlite.Write, { run_id : Str, repository : Str, commit_sha : Str, new : Bool } => Try({}, [DbErr(Sqlite.Err)])
	add_commit! = |db, params| {
		_ = Sqlite.run_write!(db, 27, [Sqlite.Param.str(params.run_id), Sqlite.Param.str(params.repository), Sqlite.Param.str(params.commit_sha), Sqlite.Param.bool(params.new)])? # Runs.sql:24
		Ok({})
	}

	## `add_settings`, Runs.sql:28: no rows.
	add_settings! : Sqlite.Write, { run_id : Str, seed : I64, region : Str, image : Str, port : I64, rounds : I64, warmup_seconds : I64, measure_seconds : I64, open_loop_workload : Str, open_loop_shares : Str, open_loop_warmup_seconds : I64, open_loop_measure_seconds : I64, race_json : Str, versions_json : Str } => Try({}, [DbErr(Sqlite.Err)])
	add_settings! = |db, params| {
		_ = Sqlite.run_write!(db, 28, [Sqlite.Param.str(params.run_id), Sqlite.Param.i64(params.seed), Sqlite.Param.str(params.region), Sqlite.Param.str(params.image), Sqlite.Param.i64(params.port), Sqlite.Param.i64(params.rounds), Sqlite.Param.i64(params.warmup_seconds), Sqlite.Param.i64(params.measure_seconds), Sqlite.Param.str(params.open_loop_workload), Sqlite.Param.str(params.open_loop_shares), Sqlite.Param.i64(params.open_loop_warmup_seconds), Sqlite.Param.i64(params.open_loop_measure_seconds), Sqlite.Param.str(params.race_json), Sqlite.Param.str(params.versions_json)])? # Runs.sql:43
		Ok({})
	}

	## `add_version`, Runs.sql:51: no rows.
	add_version! : Sqlite.Write, { run_id : Str, name : Str, version : Str } => Try({}, [DbErr(Sqlite.Err)])
	add_version! = |db, params| {
		_ = Sqlite.run_write!(db, 29, [Sqlite.Param.str(params.run_id), Sqlite.Param.str(params.name), Sqlite.Param.str(params.version)])? # Runs.sql:55
		Ok({})
	}

	## `add_competitor`, Runs.sql:58: no rows.
	add_competitor! : Sqlite.Write, { run_id : Str, name : Str, position : I64, title : Str, language : Str, framework : Str } => Try({}, [DbErr(Sqlite.Err)])
	add_competitor! = |db, params| {
		_ = Sqlite.run_write!(db, 30, [Sqlite.Param.str(params.run_id), Sqlite.Param.str(params.name), Sqlite.Param.i64(params.position), Sqlite.Param.str(params.title), Sqlite.Param.str(params.language), Sqlite.Param.str(params.framework)])? # Runs.sql:65
		Ok({})
	}

	## `add_workload`, Runs.sql:69: no rows.
	add_workload! : Sqlite.Write, { run_id : Str, name : Str, position : I64, title : Str, summary : Str, method : Str, path : Str, body_bytes : I64, content_type : Str, connections : I64, keepalive : Bool } => Try({}, [DbErr(Sqlite.Err)])
	add_workload! = |db, params| {
		_ = Sqlite.run_write!(db, 31, [Sqlite.Param.str(params.run_id), Sqlite.Param.str(params.name), Sqlite.Param.i64(params.position), Sqlite.Param.str(params.title), Sqlite.Param.str(params.summary), Sqlite.Param.str(params.method), Sqlite.Param.str(params.path), Sqlite.Param.i64(params.body_bytes), Sqlite.Param.str(params.content_type), Sqlite.Param.i64(params.connections), Sqlite.Param.bool(params.keepalive)])? # Runs.sql:81
		Ok({})
	}

	## `add_class`, Runs.sql:87: no rows.
	add_class! : Sqlite.Write, { run_id : Str, name : Str, position : I64, label : Str, title : Str, size : Str, loader_size : Str, server_cpu : Str } => Try({}, [DbErr(Sqlite.Err)])
	add_class! = |db, params| {
		_ = Sqlite.run_write!(db, 32, [Sqlite.Param.str(params.run_id), Sqlite.Param.str(params.name), Sqlite.Param.i64(params.position), Sqlite.Param.str(params.label), Sqlite.Param.str(params.title), Sqlite.Param.str(params.size), Sqlite.Param.str(params.loader_size), Sqlite.Param.str(params.server_cpu)])? # Runs.sql:96
		Ok({})
	}

	## `end`, Runs.sql:101: no rows.
	end! : Sqlite.Write, { status : Str, reason : Str, finished_at : Str, seconds : F64, build_seconds : F64, launch_seconds : F64, racing_seconds : F64, cost_usd : F64, id : Str } => Try({}, [DbErr(Sqlite.Err)])
	end! = |db, params| {
		_ = Sqlite.run_write!(db, 33, [Sqlite.Param.str(params.status), Sqlite.Param.str(params.reason), Sqlite.Param.str(params.finished_at), Sqlite.Param.f64(params.seconds), Sqlite.Param.f64(params.build_seconds), Sqlite.Param.f64(params.launch_seconds), Sqlite.Param.f64(params.racing_seconds), Sqlite.Param.f64(params.cost_usd), Sqlite.Param.str(params.id)])? # Runs.sql:111
		Ok({})
	}

	## `add_droplet`, Runs.sql:116: no rows.
	add_droplet! : Sqlite.Write, { run_id : Str, position : I64, role : Str, class : Str, size : Str, price_hourly : F64, seconds : F64, cost_usd : F64 } => Try({}, [DbErr(Sqlite.Err)])
	add_droplet! = |db, params| {
		_ = Sqlite.run_write!(db, 34, [Sqlite.Param.str(params.run_id), Sqlite.Param.i64(params.position), Sqlite.Param.str(params.role), Sqlite.Param.str(params.class), Sqlite.Param.str(params.size), Sqlite.Param.f64(params.price_hourly), Sqlite.Param.f64(params.seconds), Sqlite.Param.f64(params.cost_usd)])? # Runs.sql:125
		Ok({})
	}

	## A row of `access`.
	Access : { status : Str, worker_token : Sqlite.Nullable(Str) }

	## `access`, Runs.sql:132: one row, or `NotFound`.
	access! : Sqlite.Read, { id : Str } => Try(Access, [NotFound, DbErr(Sqlite.Err)])
	access! = |db, params| {
		rows = Sqlite.run_read!(db, 35, [Sqlite.Param.str(params.id)])? # Runs.sql:134
		match rows {
			[] => Err(NotFound)
			[[c0, c1]] => Ok({ status: Sqlite.Cell.str(c0), worker_token: Sqlite.Cell.nullable_str(c1) })
			_ => crash "roux-db: Runs.access: rows the host should have refused"
		}
	}

	## `set_class`, Runs.sql:136: no rows.
	set_class! : Sqlite.Write, { run_id : Str, class : Str, status : Str, reason : Str, seconds : F64 } => Try({}, [DbErr(Sqlite.Err)])
	set_class! = |db, params| {
		_ = Sqlite.run_write!(db, 36, [Sqlite.Param.str(params.run_id), Sqlite.Param.str(params.class), Sqlite.Param.str(params.status), Sqlite.Param.str(params.reason), Sqlite.Param.f64(params.seconds)])? # Runs.sql:142
		Ok({})
	}

	## `set_machine`, Runs.sql:148: no rows.
	set_machine! : Sqlite.Write, { run_id : Str, class : Str, role : Str, size : Str, cpu : Str, cpus : I64, kernel : Str, cpu_id : Str, cpu_wanted : Str, cpu_matched : Bool, attempts : I64 } => Try({}, [DbErr(Sqlite.Err)])
	set_machine! = |db, params| {
		_ = Sqlite.run_write!(db, 37, [Sqlite.Param.str(params.run_id), Sqlite.Param.str(params.class), Sqlite.Param.str(params.role), Sqlite.Param.str(params.size), Sqlite.Param.str(params.cpu), Sqlite.Param.i64(params.cpus), Sqlite.Param.str(params.kernel), Sqlite.Param.str(params.cpu_id), Sqlite.Param.str(params.cpu_wanted), Sqlite.Param.bool(params.cpu_matched), Sqlite.Param.i64(params.attempts)])? # Runs.sql:160
		Ok({})
	}
}
