# Generated by roux build from Bottom.rocstache. DO NOT EDIT.
# Its contract only: markup changes leave this file alone.
import pf.Rocstache
import Templates

Bottom :: [].{

	## What `Bottom.rocstache` reads, inferred from its tags.
	Ctx : {}

	## The template's value: what a response sends, rendered by the
	## host from the template's bytecode as it is sent.
	template : Ctx -> Rocstache.Template(Templates.Template)
	template = |ctx| { layouts: Templates.layouts, template: Bottom(ctx) }
}
