# Generated by roux build from HistoryPage.rocstache. DO NOT EDIT.
# Its contract only: markup changes leave this file alone.
import pf.Rocstache
import Templates

HistoryPage :: [].{

	## What `HistoryPage.rocstache` reads, inferred from its tags.
	Ctx : {
		classes : List(
			{
				charts : List(
					{
						dates : List({ label : Str, x : Str }),
						empty : Bool,
						lines : List(
							{
								competitor : Str,
								dots : List(
									{
										cx : Str,
										cy : Str,
										r : Str,
										title : Str,
									},
								),
								drawn : Bool,
								label_x : Str,
								label_y : Str,
								path : Str,
							},
						),
						ticks : List(
							{ label : Str, line_y : Str, text_y : Str },
						),
						title : Str,
					},
				),
				title : Str,
			},
		),
		competitors : List(Str),
		home : Bool,
		nav : List({ current : Bool, href : Str, label : Str }),
		note : Str,
		tabs : List({ action : Str, current : Bool, href : Str, label : Str }),
		title : Str,
		waiting : Bool,
	}

	## The template's value: what a response sends, rendered by the
	## host from the template's bytecode as it is sent.
	template : Ctx -> Rocstache.Template(Templates.Template)
	template = |ctx| { layouts: Templates.layouts, template: HistoryPage(ctx) }
}
