# Generated by roux build from HistoryChart.rocstache. DO NOT EDIT.
# Its contract only: markup changes leave this file alone.
import pf.Rocstache
import Templates

HistoryChart :: [].{

	## What `HistoryChart.rocstache` reads, inferred from its tags.
	Ctx : {
		dates : List({ label : Str, x : Str }),
		empty : Bool,
		lines : List(
			{
				competitor : Str,
				dots : List({ cx : Str, cy : Str, r : Str, title : Str }),
				drawn : Bool,
				label_x : Str,
				label_y : Str,
				path : Str,
			},
		),
		ticks : List({ label : Str, line_y : Str, text_y : Str }),
		title : Str,
	}

	## The template's value: what a response sends, rendered by the
	## host from the template's bytecode as it is sent.
	template : Ctx -> Rocstache.Template(Templates.Template)
	template = |ctx| { layouts: Templates.layouts, template: HistoryChart(ctx) }
}
