# Generated by roux build from IndexPage.rocstache. DO NOT EDIT.
# Its contract only: markup changes leave this file alone.
import pf.Rocstache
import Templates

IndexPage :: [].{

	## What `IndexPage.rocstache` reads, inferred from its tags.
	Ctx : {
		classes : List(
			{
				h2c : List(
					{
						rows : List(
							{
								competitor : Str,
								h2c : Str,
								http2_change : Str,
								plain : Str,
								tls : Str,
								tls_change : Str,
							},
						),
						strips : List(
							{
								rows : List(
									{
										competitor : Str,
										high : Str,
										hollow : Bool,
										low : Str,
										ranged : Bool,
										reach : Str,
										share : Str,
										tip : Str,
										valid : Bool,
										value : Str,
									},
								),
								summary : Str,
								table : List(
									{
										competitor : Str,
										cpu : Str,
										limit : Str,
										loader : Str,
										net : Str,
										note : Str,
										p95 : Str,
										p99 : Str,
										p999 : Str,
										rounds : Str,
										rps : Str,
										rss : Str,
										spread : Str,
										steal : Str,
										valid : Bool,
									},
								),
								title : Str,
							},
						),
					},
				),
				intro : Str,
				machines : List({ role : Str, text : Str }),
				name : Str,
				open : List(
					{
						caption : Str,
						lines : List(
							{
								competitor : Str,
								dots : List(
									{
										cx : Str,
										cy : Str,
										hollow : Bool,
										title : Str,
									},
								),
								label_x : Str,
								label_y : Str,
								path : Str,
							},
						),
						measure : Str,
						ticks_x : List({ label : Str, x : Str }),
						ticks_y : List(
							{ label : Str, line_y : Str, text_y : Str },
						),
						title : Str,
					},
				),
				strips : List(
					{
						rows : List(
							{
								competitor : Str,
								high : Str,
								hollow : Bool,
								low : Str,
								ranged : Bool,
								reach : Str,
								share : Str,
								tip : Str,
								valid : Bool,
								value : Str,
							},
						),
						summary : Str,
						table : List(
							{
								competitor : Str,
								cpu : Str,
								limit : Str,
								loader : Str,
								net : Str,
								note : Str,
								p95 : Str,
								p99 : Str,
								p999 : Str,
								rounds : Str,
								rps : Str,
								rss : Str,
								spread : Str,
								steal : Str,
								valid : Bool,
							},
						),
						title : Str,
					},
				),
				title : Str,
			},
		),
		commits : List({ name : Str, short : Str, url : Str }),
		competitors : List(Str),
		home : Bool,
		id : Str,
		nav : List({ current : Bool, href : Str, label : Str }),
		racer : List({ items : List(Str), text : Str }),
		ready : Bool,
		sections : List({ action : Str, current : Bool, href : Str, label : Str }),
		started : Str,
		tabs : List({ action : Str, current : Bool, href : Str, label : Str }),
		timed : Bool,
		title : Str,
		took : Str,
	}

	## The template's value: what a response sends, rendered by the
	## host from the template's bytecode as it is sent.
	template : Ctx -> Rocstache.Template(Templates.Template)
	template = |ctx| { layouts: Templates.layouts, template: IndexPage(ctx) }
}
