# Generated by roux build from Strip.rocstache. DO NOT EDIT.
# Its contract only: markup changes leave this file alone.
import pf.Rocstache
import Templates

Strip :: [].{

	## What `Strip.rocstache` reads, inferred from its tags.
	Ctx : {
		rows : List(
			{
				competitor : Str,
				high : Str,
				hollow : Bool,
				low : Str,
				ranged : Bool,
				reach : Str,
				share : Str,
				tip : Str,
				valid : Bool,
				value : Str,
			},
		),
		summary : Str,
		table : List(
			{
				competitor : Str,
				cpu : Str,
				limit : Str,
				loader : Str,
				net : Str,
				note : Str,
				p95 : Str,
				p99 : Str,
				p999 : Str,
				rounds : Str,
				rps : Str,
				rss : Str,
				spread : Str,
				steal : Str,
				valid : Bool,
			},
		),
		title : Str,
	}

	## The template's value: what a response sends, rendered by the
	## host from the template's bytecode as it is sent.
	template : Ctx -> Rocstache.Template(Templates.Template)
	template = |ctx| { layouts: Templates.layouts, template: Strip(ctx) }
}
