# Generated by roux build from WorkloadsPage.rocstache. DO NOT EDIT.
# Its contract only: markup changes leave this file alone.
import pf.Rocstache
import Templates

WorkloadsPage :: [].{

	## What `WorkloadsPage.rocstache` reads, inferred from its tags.
	Ctx : {
		groups : List(
			{
				cards : List(
					{
						route : Str,
						spec : Str,
						summary : Str,
						title : Str,
					},
				),
				heading : Str,
				note : Str,
			},
		),
		home : Bool,
		ladder : Str,
		loader_limit : Str,
		measure : Str,
		nav : List({ current : Bool, href : Str, label : Str }),
		ready : Bool,
		rounds : Str,
		shares : Str,
		title : Str,
		warmup : Str,
	}

	## The template's value: what a response sends, rendered by the
	## host from the template's bytecode as it is sent.
	template : Ctx -> Rocstache.Template(Templates.Template)
	template = |ctx| { layouts: Templates.layouts, template: WorkloadsPage(ctx) }
}
